### ISSUE TITLE
Use Pre-existing NLP model

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#10]
Demo 2 will rely on a pre-existing NLP model. We need to determine where it is, what its expected inputs are and how we can integrate it into a elyra training pipeline. 

Acceptance Criteria:

- [x] Use pre-existing NLP model in demo 2

**Comment by Shreyanand** [comment]
Demo 2 uses pre-existing NLP models saved on S3 storage.
