### ISSUE TITLE
Demo 2 Superset dashboard

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#105]
For completing demo 2, we should have a sample Superset dashboard with the prediction table from the output of inference. This dashboard doesn't have to be very complicated, but a collection of 2 or 3 diagrams. Some ideas:

- For a selected KPI question, display answers for all the companies
- For a selected company, display answers for all the kpi questions

**Comment by MichaelClifford** [comment]
closing as a dashboard exists: https://superset-secure-odh-superset.apps.odh-cl1.apps.os-climate.org/superset/dashboard/15/?native_filters=%28%29

Re open if needed
