### ISSUE TITLE
Update Project Readme

### ISSUE THREAD

**Issue by oindrillac** [os-climate/aicoe-osc-demo#110]
The project README.md needs to be updated with the latest information and links the contents of the demos. The current README is missing a "Get Started" section for any new contributors which can provide sufficient detail on access to the cluster, environments used for running the ML workloads and a basic outline on how to get started and involved with the project.

Acceptance Criteria:
 - [x] Update Readme with up to date details on demo 1,2
 - [x] Add a Get Started section for new contributors.

**Comment by MichaelClifford** [comment]
can this be closed by #124 ?

**Comment by oindrillac** [comment]
yes 🚀

**Comment by oindrillac** [comment]
reopening this since one small addition is still needed - reflecting the changes made in #124 into https://github.com/os-climate/aicoe-osc-demo/blob/master/README.md.

Opening a PR for the same.
