### ISSUE TITLE
When sharing a screen showing Elyra console, secrets are exposed

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/aicoe-osc-demo#118]
**Is your feature request related to a problem? Please describe.**
There's a handy widget showing environment variables and their values in one of the consoles that we demo.  Alas, many of those environment variables are supposed to be secret.  When users share their screens to show how cool our Elyra pipelines are, they can leak substantial prefixes of secrets.

**Describe the solution you'd like**
It would be great if it were possible to define variables that should be obfuscated/obscured by default, and only shown when the user specifically requests visibility (which goes away after a period of time).

**Describe alternatives you've considered**

**Additional context**

@erikerlandson

**Comment by Shreyanand** [comment]
In the current version of aicoe-osc-demo, we use openshift secrets that solve this problem. I'm closing this issue but if there are any password leaks or potential leaks, feel free to create a new issue and we would prioritize it as urgent.
