### ISSUE TITLE
Should we state which base image tag is used in DockerFile for traceability?

### ISSUE THREAD

**Issue by pacospace** [os-climate/aicoe-osc-demo#122]
See: https://github.com/os-climate/aicoe-osc-demo/blob/7132a18ab915bc1193c7d234f5694994a975ab97/Dockerfile#L1 cc @erikerlandson @chauhankaranraj @MichaelClifford

**Comment by chauhankaranraj** [comment]
That sounds like a good idea :) Should we follow the same practice in our Elyra pipeline runtime images as well? e.g.: https://github.com/os-climate/aicoe-osc-demo/blob/7132a18ab915bc1193c7d234f5694994a975ab97/notebooks/demo2/preprocessing.pipeline#L17

**Comment by pacospace** [comment]
> That sounds like a good idea :) Should we follow the same practice in our Elyra pipeline runtime images as well? e.g.:
> 
> https://github.com/os-climate/aicoe-osc-demo/blob/7132a18ab915bc1193c7d234f5694994a975ab97/notebooks/demo2/preprocessing.pipeline#L17

I think so, otherwise, we cannot easily identify the source of errors in case!

**Comment by chauhankaranraj** [comment]
Yep, makes sense :+1: I'll update these then

**Comment by chauhankaranraj** [comment]
> > That sounds like a good idea :) Should we follow the same practice in our Elyra pipeline runtime images as well? e.g.:
> > https://github.com/os-climate/aicoe-osc-demo/blob/7132a18ab915bc1193c7d234f5694994a975ab97/notebooks/demo2/preprocessing.pipeline#L17
> 
> I think so, otherwise, we cannot easily identify the source of errors in case!

Yep, makes sense +1 I'll update these then
