### ISSUE TITLE
Value Error related to S3 in demo2 notebook

### ISSUE THREAD

**Issue by andraNew** [os-climate/aicoe-osc-demo#127]
Value Error related to S3 at Import in when running pdf_text_extraction.ipynb notebook from demo 2 

Error appears when running the first cell where we import libraries for pdf_text_extraction.ipynb

at this import from src.components.preprocessing import Extractor

/opt/app-root/lib64/python3.8/site-packages/boto3/resources/base.py in __init__(self, *args, **kwargs)
    116         for identifier in self.meta.identifiers:
    117             if getattr(self, identifier) is None:
--> 118                 raise ValueError(
    119                     'Required parameter {0} not set'.format(identifier))
    120 

ValueError: Required parameter bucket_name not set

![image](https://user-images.githubusercontent.com/62877651/148573042-2529a5c8-7c9d-46b6-b535-b817d99e24c0.png)

I am currently running on the aicoe-osc-demo immage with a pyhon3 kernel and vace the credentials.env set at the root

**Comment by andraNew** [comment]
@erikerlandson @MichaelClifford

**Comment by erikerlandson** [comment]
@andraNew  you might also try the "nlp text extraction" notebook image in the jh launcher menu, it might have the correct deps installed

**Comment by andraNew** [comment]
Are you refering to the Elyra server that it is used for the RuleBased Solution ? I have tried, but it did not work either

**Comment by andraNew** [comment]
@chauhankaranraj @Shreyanand  Do you have an idea of what might not be working?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj @Shreyanand Do you have an idea of what might not be working?

Hi @andraNew, I think it might be the case that the s3 credentials are not being read in correctly.

> vace the credentials.env set at the root

Do you mean that your `credentials.env` is stored at the root of your JupyterHub PVC (`/opt/app-root/src/credentials.env`), or the root of the project repo (`/opt/app-root/src/aicoe-osc-demo/credentials.env`)? Coz right now it [looks like](https://github.com/os-climate/aicoe-osc-demo/blob/9135ce63a01897d792d347fc7431f7958800e1e0/src/components/utils/kpi_mapping.py#L9) it expects the `credentials.env` to be at the root of the JupyterHub PVC.

Maybe this is an odd design and we can refine it going forward, but for now could you please try moving the .env file there and running the imports again?

**Comment by erikerlandson** [comment]
@chauhankaranraj I am confused: the cell she reported the error from only had python import statements, it had not yet attempted any `credentials.env` access

**Comment by Shreyanand** [comment]
@erikerlandson  The src.components.preprocessing imports this file: https://github.com/os-climate/aicoe-osc-demo/blob/master/src/components/utils/kpi_mapping.py and that requires a valid s3 connection. 
Issue #69 was created to remove this dependency from the original code but it was low on priority. If the credentials are found as @chauhankaranraj commented, it should fix the import error.

**Comment by andraNew** [comment]
Dear @chauhankaranraj ,
I confirm I had the credentials at the root of JupyterHub PVC .

**Comment by chauhankaranraj** [comment]
> Dear @chauhankaranraj , I confirm I had the credentials at the root of JupyterHub PVC, thus this was not the issue unfortunately

Gotcha, thanks for clarifying :smile: I think it might be the case that the kpi_mapping.py is trying to read from the [incorrect environment variables](https://github.com/os-climate/aicoe-osc-demo/blob/9135ce63a01897d792d347fc7431f7958800e1e0/src/components/utils/kpi_mapping.py#L18)?

In all the notebooks, we're using the env vars `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to extract the s3 access and secret key respectively. However this file seems to be using the env vars `S3_ACCESS_KEY` and `S3_SECRET_KEY` for the same, which might not be defined in the `credentials.env`. 

Could you please try adding `S3_ACCESS_KEY=<your_access>` and
`S3_SECRET_KEY=<your_secret>` to your credentials.env and see if that fixes the error?

**Comment by chauhankaranraj** [comment]
> Hi all,
> i have the same error. I store the credentials in the root:

Hi @DaBeIDS, just want to confirm, does this issue still persist for you if you add the `S3_BUCKET=<bucket-name-here>` and the `S3_ENDPOINT=<endpoint-url>`  variables to your credentials.env file?

**Comment by DaBeIDS** [comment]
Do you know what the bucket name it is i have to add and the endpoint-url?

**Comment by DaBeIDS** [comment]
I just realized that i do not need the correct one for the test :)
It works if i add that:
![image](https://user-images.githubusercontent.com/90916810/149192077-a547154e-1f85-4a05-9e6b-8d54cb2b8c70.png)
Then i get a new error message:
![image](https://user-images.githubusercontent.com/90916810/149192136-5d40644e-1623-40d2-80ee-be2e05a97188.png)
So then my question would be about the correct inputs.

**Comment by chauhankaranraj** [comment]
> Do you know what the bucket name it is i have to add and the endpoint-url?

Yeah, here they are: (you can also find them in the notebooks)
```
S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
S3_BUCKET=ocp-odh-os-demo-s3
```

> It works if i add that
> So then my question would be about the correct inputs.

Yes, I think just adding these inputs should fix it. Let me know if this is not the case :)

**Comment by DaBeIDS** [comment]
@chauhankaranraj: Thanks i can now execute the import :)

1) In my credential file those two have been called S3_DEV_ENDPOINT=https://s3.us-east-1.amazonaws.com and
S3_DEV_BUCKET:

![image](https://user-images.githubusercontent.com/90916810/149288681-161f2f9a-1932-459f-a9a3-c11e96c9b0cb.png)

So, i am not sure if those are needed or if actually those are the ones searched by the code.

2) I am getting then a "no credentials error" some lines later:

![image](https://user-images.githubusercontent.com/90916810/149288841-a0272b8e-c4f1-4036-a839-8a99cf797bea.png)

**Comment by andraNew** [comment]
I replaced the names of the environmental variables as suggested by @DaBeIDS , but I experience a client error right now ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
![image](https://user-images.githubusercontent.com/62877651/149320300-9a70c74c-60b4-4e5c-ab45-001449880db6.png)

**Comment by andraNew** [comment]
It actually worked when I restarted the kernel. 

In the end I had the incorect variable names that caused the issue. Thank you for your help
