### ISSUE TITLE
Define a process to setup a new experiment

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#164]
In the current version of the aicoe-osc-demo, all users access the same links in the s3 folder to run their demo. This means, all the intermediate and output files are changed every time someone runs the demo. As more people try this out, we should come up with a process to setup a new experiment that creates files specific to a user on the s3 bucket. 
One way to do this could be to have a new user edit their config file with their experiment name. Then, we create that directory on the s3 bucket with all the input files copied to it. This would ensure a different space for different experiments.

**Comment by MichaelTiemannOSC** [comment]
Even better, we should encourage users to BYOB (bring your own bucket).  That way users can be responsible for the data security of their own data, while still using the public models we are training/releasing.

**Comment by Shreyanand** [comment]
That is ideal, if the user has sensitive data and they can bring their own bucket then that should be the case. As a part of this issue, we should also update the docs on how to do that.
