### ISSUE TITLE
Create a settings file for users to configure model parameters

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#191]
The NLP demo currently has three config files: config.py, conifg_farm_train.py, and config_qa_farm_train.py.

They all configure the different parts of the process but not in a very user friendly manner and should be updated. 

There was an effort to bring a central settings.yaml in the corporate_data_pipeline repository (see [here](https://github.com/os-climate/corporate_data_pipeline/blob/release/nlp_model_v2/data/settings_default.yaml)). This settings file is then used to instantiate objects of classes in the three conifg files. The object attributes of the config classes are then used for configuring the model parameters.

One approach could be to follow that format here as well. Another approach could be to completely do away with the class structure in the  config_farm_train.py and config_qa_farm_train.py and just have a single settings.yaml file with all the user editable parameters. It boils down to the question: do we need classes and objects to configure the model or would directly reading from settings.yaml suffice? 
Directly reading from the settings.yaml seems like a more clean way of organizing as the configs classes just have model attributes and no methods, but it's open for discussion. 

cc @erikerlandson @MichaelTiemann @JeremyGohBNP

**Comment by MichaelTiemannOSC** [comment]
I think it makes a lot more sense to document settings in a single file and then farm those out (no pun intended) to whatever python initializations are needed.  Especially if we are thinking about moving to an implementation that works directly with PyTorch or directly with Haystack.  There will be some settings parameters that are specific to Farm that should be documented as such, but we should do our best to infer or impute values that make sense from general settings parameters.
