### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by JeremyGohBNP** [os-climate/aicoe-osc-demo#211]
Spawn failed. Time out when I tried to start the server. It only worked in the default configuration: 0 GPU, Small memory.

I tried with multiple configurations: did not work with 1 GPU, so I tried with CPU only but it failed too. Would it be because of Large Memory size I required?

![image](https://user-images.githubusercontent.com/82595185/193778353-023a29ef-a918-44ad-822a-75113afbe4d0.png)

**Comment by Shreyanand** [comment]
Hi @JeremyGohBNP, does the bug still persist?

**Comment by redmikhail** [comment]
@JeremyGohBNP , based on log entries your notebook is being scheduled to the regular node without GPU. I think that you need to select one of CUDA images but I hope @Shreyanand can suggest what needs to be done

**Comment by JeremyGohBNP** [comment]
The bug persists. I switched to CL1 for a demo last week.

**Comment by JeremyGohBNP** [comment]
![image](https://user-images.githubusercontent.com/82595185/194908388-84e85ae3-8c62-4589-9852-9bb6aabd32ac.png)
![image](https://user-images.githubusercontent.com/82595185/195050171-9ef2f68c-1a8d-4165-91ad-4df7e55db57e.png)
This is the configuration I set and the message error I have everytime.

**Comment by Shreyanand** [comment]
Hi Jeremy, @HumairAK confirmed that he was able to spawn both gpu and no gpu instance. Could you please try and see if it works for you?
![image (1)](https://user-images.githubusercontent.com/8916126/200368782-6b037a40-20b7-40e6-a001-a76bd72bf68a.png)
