### ISSUE TITLE
No module named "osc_ingest_trino" error

### ISSUE THREAD

**Issue by suppathak** [os-climate/aicoe-osc-demo#220]
**Describe the bug**
ModuleNotFoundError: No module named 'osc_ingest_trino'

**To Reproduce**
Run the notebook, [create_table](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/create_results_table.ipynb)

**Expected behavior**
Run without error

**Screenshots**
![Screenshot from 2022-10-25 15-52-23](https://user-images.githubusercontent.com/30439457/197896918-20f2dd47-c5c0-40ab-b5de-929f73786195.png)

**Comment by MichaelTiemannOSC** [comment]
If you haven't sorted this yet, the fix is to `pip install osc-ingest-tools`.  Then you can load the library.  How you manage your requirements.txt to provide for this (or other mechanisms for doing so) is up to you!

https://pypi.org/project/osc-ingest-tools/
