### ISSUE TITLE
Couldn't add Kubeflow Pipelines runtime configuration

### ISSUE THREAD

**Issue by Jeevi281** [os-climate/aicoe-osc-demo#226]
I tried to add new kubeflow pipelines runtime, i entered the credentials and saved and closed it. Still the runtime is not added.

**Comment by Shreyanand** [comment]
Hi @Jeevi281, could you please write the steps to reproduce the error and add screenshot if possible? A good format to follow would be the issue template for bug report.

**Comment by Jeevi281** [comment]
Okay sure @Shreyanand
