### ISSUE TITLE
KeyError: 'TRINO_PASSWD'

### ISSUE THREAD

**Issue by Jeevi281** [os-climate/aicoe-osc-demo#233]
**Describe the bug**
While executing the 'create result table' notebook got this error -> KeyError: 'TRINO_PASSWD'. So, I tried using JWT token as well as github pwd in place of TRINO pwd in credentials. Still the error persists.

**To Reproduce**
After started running the inference pipeline
1. Go to 'kubeflow '
2. Click on 'Runs'

![Screenshot (228)](https://user-images.githubusercontent.com/116078421/200768044-92411ed7-4934-46f8-96a5-daa49f3616b0.png)

**Expected behavior**
Successful execution without any errors

**Comment by Shreyanand** [comment]
@Jeevi281 The create_results_table notebook creates a Trino table that can be queried using SQL like commands. You need to put the Trino database credentials in the pipeline property of the notebook. This [image](https://github.com/os-climate/aicoe-osc-demo/blob/master/docs/assets/demo2-notebook-properties.png) in Elyra pipeline doc shows where you have to enter them. The documentation [here](https://github.com/os-climate/aicoe-osc-demo/blob/master/docs/access-jh.md) and [here](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md#4-set-your-credentials-environment-variables) specifies how to get your JWT token from [here](das-odh-trino.apps.odh-cl2.apps.os-climate.org)
