### ISSUE TITLE
TrinoUserError

### ISSUE THREAD

**Issue by Jeevi281** [os-climate/aicoe-osc-demo#238]
**Describe the bug**
Getting error while executing create_result_table notebook

**To Reproduce**
After started running the pipeline
1. Go to 'kubeflow'
2. Click on 'Runs'
![Screenshot (232)](https://user-images.githubusercontent.com/116078421/202092085-0e8935c0-839c-4f26-883c-1dda9d3bd28c.png)

**Error Message:**
TrinoUserError: TrinoUserError(type=USER_ERROR, name=INVALID_TABLE_PROPERTY, message="Catalog 'osc_datacommons_dev' table property 'external_location' does not exist", query_id=20221116_050359_00160_hqiev)

**Expected behavior**
To execute susscessfully without any error

**Screenshots**

**Additional context**

**Comment by HeatherAck** [comment]
@erikerlandson can you please take a look

**Comment by Jeevi281** [comment]
@erikerlandson can you please help with this?

**Comment by HeatherAck** [comment]
adding @rynofinn and @Shreyanand

**Comment by HeatherAck** [comment]
@Jeevi281 - can u let us know if you are using osc ingest tools?  can you let us know what version of software / image you are using and notebook? - please provide us link to github

**Comment by Shreyanand** [comment]
@Jeevi281 this seems like an old version of the notebook. You could pull in the latest changes from this repository that has the updated [create_results_table notebook](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/create_results_table.ipynb) that uses the iceberg catalog. 
I'm working on creating a new docker image that includes the latest code directly.

On a separate note, what is your aim in running these notebooks? If you can describe your use case, I'd be able help better.

**Comment by HeatherAck** [comment]
@Jeevi281 - we assume the version is the problem.  closing - please reopen if you have issues
