### ISSUE TITLE
Create a JH image for running extraction and curation on OS climate JH cluster

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#25]
While running the extraction and curation notebook, we encountered this error
![Screenshot from 2021-09-29 11-23-54](https://user-images.githubusercontent.com/8916126/135299944-98d4778a-c7be-4ca0-b765-1dae7ed09f06.png)

It seems that we'd require root access to get this dependency installed. To be able to run it on the cluster and later with KF pipelines, we will need an image that has this dependency installed.
cc @chauhankaranraj

**Comment by MichaelClifford** [comment]
Is this for demo 2?

**Comment by chauhankaranraj** [comment]
> Is this for demo 2?

Yep, one of the dependencies in a notebook for demo 2 seems to need a access to a system file

**Comment by Shreyanand** [comment]
Fixed in https://github.com/os-climate/aicoe-osc-demo/pull/33 and successive image builds.
