### ISSUE TITLE
Update how config parameters are passed

### ISSUE THREAD

**Issue by chauhankaranraj** [os-climate/aicoe-osc-demo#44]
Currently in the notebooks the parameters like data read/write dir, model save/load dir, etc. are passed through config.py, which is a part of `src`. However, since `src` is being installed as a package into the JupyterHub image, the default directory locations get set to `/opt/app-root/lib/python3.8/site-packages/data/*`, `/opt/app-root/lib/python3.8/site-packages/checkpoints/*`, etc. which won't exist at runtime. Additionally, it is unclear if "baking config params into src" is better than passing them as env variables or file dependencies in Elyra pipelines.

One suggestion we had was to we move config.py to _not_ be a part of src, but rather just a file in this repo. This way it can be imported as a file during runtime and the default file paths would resolved according to where it is being imported (instead of `site-packages/*`.

Acceptance Criteria
- [ ] Move config.py outside src
- [ ] Update notebooks to read config params from here

**Comment by MichaelClifford** [comment]
:+1:
