### ISSUE TITLE
Fix demo 2 image: add Poppler utils linux dependency

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#45]
The text and table extraction from pdfs are done using a python package _pdf2image_ that requires [poppler](https://poppler.freedesktop.org/) utils. On my local, I was able to sudo get it but we need to install it in the image as well. 
The package seems like to be a hard requirement for table extraction #28. 
![Screenshot from 2021-10-13 15-07-49](https://user-images.githubusercontent.com/8916126/137202357-d4729ddb-f520-4215-ac49-ee6c544fa3fe.png)

**Comment by harshad16** [comment]
we can do that by creating a **Dockerfile** with s2i induced.
The process to do that is using s2i: 
`s2i build . quay.io/thoth-station/s2i-elyra-custom-notebook:latest  --loglevel=0 --scripts-url="image:///opt/app-root/builder" --as-dockerfile Dockerfile`


Anyhow, this is the solution needed for this:

Dockerfile:
```
FROM quay.io/thoth-station/s2i-elyra-custom-notebook:latest
LABEL name="aicoe-osc-demo" \
      summary="" \
      description=""
      "io.openshift.s2i.scripts-url"="image:///opt/app-root/builder" \
      "io.openshift.s2i.build.image"="quay.io/thoth-station/s2i-elyra-custom-notebook:latest" 

ENV JUPYTER_ENABLE_LAB="1" \
    ENABLE_MICROPIPENV="1" \
    THAMOS_RUNTIME_ENVIRONMENT="" \
    THOTH_ADVISE="0" \
    THOTH_ERROR_FALLBACK="1" \
    THOTH_DRY_RUN="1" \
    THAMOS_DEBUG="0" \
    THAMOS_VERBOSE="1" \
    THOTH_PROVENANCE_CHECK="0"
USER root

<install other packages>

# Copying in override assemble/run scripts
COPY .s2i/bin /tmp/scripts
# Copying in source code
COPY . /tmp/src
# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/scripts /tmp/src
USER 1001
RUN /tmp/scripts/assemble
CMD /tmp/scripts/run

```

**Comment by harshad16** [comment]
once created the docker file change the config in the `.aicoe-ci.yaml`

```
  build-stratergy: Dockerfile
  dockerfile-path: Dockerfile
   custom-tag: latest
   registry: quay.io
   registry-org: os-climate
   registry-project: aicoe-osc-demo
   registry-secret: os-climate-pusher-secret
```

**Comment by Shreyanand** [comment]
Thanks @harshad16 the new docker file works and we have poppler installed.
