### ISSUE TITLE
Add demo repository to list of jh images on the spawner page 

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#5]
We should be able to start our demo from the JH spawner UI on the OS-Climate Cluster. We have an existing [tutorial](https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md) that shows how to add repo content images to the list of available images to be spawned by JH. 

Acceptance Criteria:

- [x] This repo can be selected as a content image from the JH spawner on the OS-Climate cluster

**Comment by chauhankaranraj** [comment]
Closed by operate-first/apps#1108
