### ISSUE TITLE
Requirements for running the training phase

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#51]
Reading the training [notebook](https://github.com/os-climate/corporate_data_pipeline/blob/main/Allianz_NLP/model_pipeline/notebooks/Demo_ESG_data_training_Jul_25.ipynb) for the QA task, it looks like we would need a pretrained _relevance roberta_ model at this location `file_config.saved_models_dir/relevance_roberta`.  
To start the process of fine tuning, we need to have the right base model. Is the base model publicly available?

**Comment by ChristianMeyndt** [comment]
@MichaelClifford I think the best way would be to use the roberta-model that we have used so far in our local solution. Is it possible to upload it somewhere on S3? It should be also publicly available somewhere, but I did not find exactly what we are using quickly.

**Comment by ChristianMeyndt** [comment]
@MichaelClifford  Additionally we should also upload the models that we have trained on our side. Because until we are able to train new models for OS-C we should use them for further testing.

**Comment by MichaelClifford** [comment]
@ChristianMeyndt Yes, I think having all the models available on S3 is a good way to go. I think we could use the `ocp-odh-os-demo-s3` bucket and use the directory prefix convention `shared_models/<model_name>/<version_number>`. Let me know if anyone has an objection to that :slightly_smiling_face:
