### ISSUE TITLE
Create Superset Dashboard 

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#6]
Create a basic Superset dashboard on os-climate cluster with the available data showing some basic stats and ensure the trino/cloudbeaver/superset connections are working correctly. 

Acceptance Criteria:
- [x] Create a basic Superset dashboard with the available data
- [x] Showing some basic stats on the dataset
- [x] Ensure the trino/cloudbeaver/superset connections are working correctly.

**Comment by oindrillac** [comment]
The connections between S3 storage, Trino, Superset work as expected. Apart from the tables and charts which already exist and were created by @erikerlandson, we tried creating additional charts and dashboards to make sure the connections are working.

We read the `fundamental_data` sheet from S3 storage > which has a table `fundamental_data` in the schema `company_data` in db `demo1` in Trino > this has an imported dataset `fundamental_dataset` in SuperSet > using which we are able to create charts in Superset such as:

![image](https://user-images.githubusercontent.com/32435206/133832327-1da229db-0024-4b50-b79d-15aafd462cd3.png)

**Comment by aakankshaduggal** [comment]
Link to dashboard : https://superset-secure-odh-superset.apps.odh-cl1.apps.os-climate.org/superset/dashboard/2/
