### ISSUE TITLE
Demo 2 Video Recording

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#60]
Record a demo of demo 12. Post to youtube channel and link in demo2/readme.

**Comment by Shreyanand** [comment]
Update: First half of the demo [video](https://drive.google.com/file/d/1ETSOBG9wMXZ7rsSHA_G6e4IsxYPs0DBB/view?usp=sharing). 
To be merged with the other half being recorded by @chauhankaranraj.

**Comment by chauhankaranraj** [comment]
> Update: First half of the demo [video](https://drive.google.com/file/d/1ETSOBG9wMXZ7rsSHA_G6e4IsxYPs0DBB/view?usp=sharing).
> To be merged with the other half being recorded by @chauhankaranraj.

Second half of the demo video is available [here](https://drive.google.com/file/d/1eA3V5FWEFqxUdHRPK07TOym03Maz2nyy/view?usp=sharing). Let me know what you think :)

**Comment by Shreyanand** [comment]
Final stitched and processed [video](https://drive.google.com/file/d/1W3GTkqIYwBjPKdFkUZmXYFspPGCCa2MJ/view?usp=sharing).

**Comment by MichaelClifford** [comment]
Actually, this needs to be uploaded to youtube first so that we can share it

**Comment by Shreyanand** [comment]
Youtube unlisted [video](https://youtu.be/lGeT615YNlM). Will make it public once up-voted :)

**Comment by oindrillac** [comment]
Video demo looks great. Great work @Shreyanand @chauhankaranraj 👍
