### ISSUE TITLE
Demo 2 README

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#61]
We need to add a README.md to `/notebooks/demo2` that provides sufficient detail for someone with access to the os-c cluster to run all notebooks, run the elyra pipeline and interact with the deployed model service. The goal is to show off how we leverage ODH tools and DS best practices as a guide that can be used by others interested in developing model training/inference workloads in the os-c project.

**Comment by oindrillac** [comment]
@chauhankaranraj @Shreyanand Can this be closed by #108 and #71 ?

**Comment by Shreyanand** [comment]
Almost, so we recently added a Superset dashboard, we could update that in the Readme. I think once we record the demo we should have everything in place to close this as well.

**Comment by oindrillac** [comment]
> Almost, so we recently added a Superset dashboard, we could update that in the Readme. 

cool! lets link that then.

> I think once we record the demo we should have everything in place to close this as well.

I see that is being captured in #60
