### ISSUE TITLE
Create a openshift secret for ocp-odh-os-demo-s3

### ISSUE THREAD

**Issue by oindrillac** [os-climate/aicoe-osc-demo#68]
Create an openshift secret for `ocp-odh-os-demo-s3`, such that access key and secret key can be passed through the secret during [creation](https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html#cloud-object-storage-credentials-secret-cos-secret) of kubeflow pipelines runtime.

**Comment by MichaelClifford** [comment]
@HumairAK @4n4nd anything we should do to push this forward?

**Comment by HumairAK** [comment]
Sorry missed this, will work on it today.

**Comment by HumairAK** [comment]
created https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/kubeflow/secrets/ocp-odh-os-demo-s3

**Comment by oindrillac** [comment]
confirming that this works in the pipeline, closing.
