### ISSUE TITLE
Remove kpi-mapping.py from source package

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#69]
kpi-mapping.py interacts with s3 and requires credentials to execute. The file is then imported by table and text extractor classes making them dependent on the s3 connection as well.  Based on the interaction _https://github.com/os-climate/aicoe-osc-demo/pull/63#r733931677_, if we connect to s3 in pdf_table_curation.ipynb and pdf_text_curation.ipynb and then pass the kpi-mappings to the text and table extractor classes, we would decouple ceph communication code from the data preprocessing code.

Acceptance

- [ ] Change text_curator.py and table_curator.py files to get mappings from parameters and not from an imported kpi-mapping file. 
- [ ] Update pdf_table_curation.ipynb and pdf_text_curation.ipynb  accordingly.

**Comment by erikerlandson** [comment]
IIUC, a reasonable fix here is to simply remove the credentials loading:
https://github.com/os-climate/aicoe-osc-demo/blob/master/src/components/utils/kpi_mapping.py#L7

If one tries to execute this code, it should fail at line 16 where it tries to access undefined environment vars.

A related fix to the notebook itself would be to load the credentials in a cell before these imports, with a note explaining that the following `import` actually executes code (as opposed to just defining functions and classes, etc) that requires expected credential env-vars.

**Comment by erikerlandson** [comment]
@MichaelClifford I think the problem is not a `.py` file interating w/ s3, it is that an `import` statement is causing an s3 error. At least, that is what confused me.
