### ISSUE TITLE
Prepare Demo 2 for Serving Model Inferences

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#8]
Demo 2 will involve serving a model and interacting with its deployed endpoint. This requires us to prepare a flask app, similar to [this one](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/wsgi.py), as well as the appropriate set of manifests, similar to [these]( https://github.com/AICoE/elyra-aidevsecops-tutorial/tree/master/manifests/base).

Acceptance Criteria:

- [ ] Create a flask app to serve inferences
- [ ] Create manifests to deploy app on OpenShift

**Comment by MichaelTiemannOSC** [comment]
Closing due to completed Epic mentioned above.
