### ISSUE TITLE
Jupyterhub image build error

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#87]
Trying the 9th release of the project image, my JH gave this error:
![Screenshot from 2021-11-02 19-27-58](https://user-images.githubusercontent.com/8916126/139965716-ec93c8c1-3393-414c-a783-307ae2769907.png)
![Screenshot from 2021-11-02 19-29-37](https://user-images.githubusercontent.com/8916126/139965757-27d06d5d-29a8-466d-b951-c236c0cf4ad1.png)

Steps to reproduce:

1. Go to https://jupyterhub-odh-jupyterhub.apps.odh-cl1.apps.os-climate.org/
2. Select AICoE OSC demo image

**Comment by HumairAK** [comment]
it seemed to create fine for me, can someone else confirm the same error?

**Comment by harshad16** [comment]
i m not authorized to use the URL, sorry cant reproduce it.

**Comment by Shreyanand** [comment]
> it seemed to create fine for me, can someone else confirm the same error?

Could you please try again? We had to revert the image to an older version for a demo, maybe that's why it worked for you. Now the image is back to the latest, and broken version.

**Comment by Shreyanand** [comment]
@HumairAK @harshad16 I tried building the image locally and it was built without any errors. However, when I ran it, the Jupyterhub instance on my localhost showed `this site can't be reached`. Probably because of the same reason...

**Comment by HumairAK** [comment]
@Shreyanand that seems to suggest an issue with the image and not an ops related issue, right? @4n4nd do you have any idea here?

**Comment by 4n4nd** [comment]
yeah this is an issue with the image.
@harshad16 can confirm

**Comment by harshad16** [comment]
I will check and re-confirm on this :+1:

**Comment by chauhankaranraj** [comment]
Hey folks, so it seems that removing `jupyter` and `jupyterlab` from Pipfile/Pipfile.lock, and then building the image fixes this issue (tested only locally). I can update the Pipfile on the repo and re-release and see if it works.

**Comment by harshad16** [comment]
> @HumairAK @harshad16 I tried building the image locally and it was built without any errors. However, when I ran it, the Jupyterhub instance on my localhost showed `this site can't be reached`. Probably because of the same reason...

I have tried to build the image with no configuration change. and ran it on system it runs successfully.
![osc](https://user-images.githubusercontent.com/14028058/140373213-cdf46bfd-c726-4983-877a-f74b23be80fb.png)

**Comment by harshad16** [comment]
> Hey folks, so it seems that removing `jupyter` and `jupyterlab` from Pipfile/Pipfile.lock, and then building the image fixes this issue (tested only locally). I can update the Pipfile on the repo and re-release and see if it works.

very good point, why were these package installed explicitly?

**Comment by chauhankaranraj** [comment]
> very good point, why were these package installed explicitly?

IIRC while we were testing image build locally, one of the training notebooks wouldn't work until we had ipywidgets installed, which in turn required these packages. But I think for now we should be able to go without these included in Pipfile.

**Comment by MichaelClifford** [comment]
can we close this issue?

**Comment by HumairAK** [comment]
Do you folks think others would benefit from from these resolution steps in the future? If so can we get a small contribution to the JH docs runbook here: https://github.com/operate-first/apps/blob/master/docs/odh/jupyterhub/runbook.md ?  :smiley:

**Comment by MichaelTiemannOSC** [comment]
This link is now 404: https://github.com/operate-first/apps/blob/master/docs/odh/jupyterhub/runbook.md

Pretty sure that the notebook requiring ipywidgets is the (interactive) annotation tool.

**Comment by Shreyanand** [comment]
The latest version of the image run without any errors.
