### ISSUE TITLE
Run relevance infer for kpis 9-12

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#88]
On a closer inspection of the relevance infer output, all csvs in output infer folder have answers for only one question: "What is the company name?" The `run_folder` method needs to be examined and run for kpis 9-12.

**Comment by Shreyanand** [comment]
On reducing the kpis to 9-12, we get 0 relevant paragraphs for each question which should not be the case. 
![Screenshot from 2021-11-03 16-18-38](https://user-images.githubusercontent.com/8916126/140186430-56e1f71e-5138-4b33-9696-59869cdc3c53.png)
Debugging.

**Comment by Shreyanand** [comment]
@chauhankaranraj latest still points to v0.9.0...

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj latest still points to v0.9.0...

It needed to be manually updated, but should be fixed now

**Comment by Shreyanand** [comment]
#92 fixed the error and the demo works for kpis 9-12. Reference [pipeline](http://ml-pipeline-ui-kubeflow.apps.odh-cl1.apps.os-climate.org/pipeline/#/runs/details/cdf2d92d-ecd0-4990-b024-9e5960f40e17).
