### ISSUE TITLE
Create modified ingestion pipeline from demo 1 to interact with output from demo 2

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#94]
Create a modified version of `demo1-create-tables.ipynb` to push demo 2 prediction results csv into trino. The data schema should be inferred from the csv. 

Acceptance Criteria:
- [ ] Read infer kpi files from `/ocp-odh-os-demo-s3/corpdata/ESG/pipeline_run/samples_4/infer_KPI`
- [ ] Create a modified version of create table and push the results to Trino
- [ ] Add a pipeline for demo3

**Comment by aakankshaduggal** [comment]
Thanks @Shreyanand! We can get started with this :smile:
