### ISSUE TITLE
Demo 3 Readme

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#96]
We need to add a README.md to /notebooks/demo3 that provides sufficient detail for someone with access to the os-c cluster to run all notebooks, run the elyra pipeline and interact with data stored in trino. The goal is to show off how we leverage ODH tools and DS best practices as a guide that can be used by others interested in developing end-2-end ML workloads in the os-c project.

**Comment by Shreyanand** [comment]
This issue is being tracked as a part of demo 2 Readme (issue #61).
